### ISSUE TITLE
Tags & Releases

### ISSUE THREAD

**Issue by cbortz** [healthify/fake_idp#15]
- Should we be tagging commits?
- Should we be created releases?

What should our approach be?

**Comment by cbortz** [comment]
Created a release for [v0.4.0](https://github.com/healthify/fake_idp/releases/tag/v0.4.0). Any thoughts about formatting here?

**Comment by samudary** [comment]
@cbortz I think we should be creating releases for any public gems. Created a release for the last body of work: https://github.com/healthify/fake_idp/releases/tag/0.5.0

I'm flexible with the format as long as it provides general details on the changes made.

**Comment by cbortz** [comment]
We've started doing this already so I am going to close this issue.
