### ISSUE TITLE
Cannot turn off encryption via environment variables 

### ISSUE THREAD

**Issue by ireneybean** [healthify/fake_idp#38]
The `default_encryption` method always returns true for two reasons
- `false || true` is `true`
- environment values come in as strings, so even if the `ENV['ENCRYPTION_ENABLED']` is set to `false`, a string with value `false` is still truthy.

I'll submit a pull request for this.

**Comment by samudary** [comment]
Fixed via https://github.com/healthify/fake_idp/pull/39

**Comment by cbortz** [comment]
@ireneybean Just a heads up that these changes have been bundled into [version 1.0.0](https://github.com/healthify/fake_idp/releases/tag/1.0.0). With this release, we've also published the gem to RubyGems! Thanks again for your contributions.

https://rubygems.org/gems/fake_idp

**Comment by ireneybean** [comment]
Awesome! Thanks for the update.
