### ISSUE TITLE
Update activesupport dependency

### ISSUE THREAD

**Issue by AlecRust** [healthify/fake_idp#44]
It's great that `fake_idp` is [now published](https://github.com/healthify/fake_idp/issues/16) to RubyGems (maybe README should be updated with this) but sadly I still have to load this gem from GitHub to pin it to a version before you added a dependency on Active Support 5.

Our app is running Rails 6.0.3.5 which depends on `activesupport (= 6.0.3.5)`, but this gem [depends](https://github.com/healthify/fake_idp/blob/5c4d9ec835aeaa1e4d323ac0a830b4f56cd94bcd/fake_idp.gemspec#L27) on `activesupport (~> 5.2.4.3)`. Any chance you could update your Active Support dependency?

**Comment by tylerwillingham** [comment]
@AlecRust sorry for the delayed response. We'll work on prioritizing a change to prevent that `activesupport` from being a blocker

**Comment by tylerwillingham** [comment]
Pull request #47 will track the evolution of this change

**Comment by AlecRust** [comment]
Thanks! Any chance you could publish a new release with this change?

**Comment by tylerwillingham** [comment]
@AlecRust 1.0.2 was pushed by @k-peek on 4/16 to RubyGems 😄

**Comment by AlecRust** [comment]
Cool. Now it's just `ruby-saml ~> 1.11.0` causing a problem 😄

**Comment by tylerwillingham** [comment]
@AlecRust I took a quick glance at the CHANGELOG for `ruby-saml` and I think we should be fine to lock to a version <= 1.12.0 (it doesn't look like they always respect semver, but I'm open to being wrong). Our team has a lot of things in flight at the moment so if you'd like to make a PR allowing for a higher limit for that dependency I'd be happy to give it a review and own the release over the next 1-2 weeks.

**Comment by AlecRust** [comment]
Cheers done https://github.com/healthify/fake_idp/pull/48.

**Comment by tylerwillingham** [comment]
@AlecRust 1.0.3 has been pushed to rubygems

**Comment by AlecRust** [comment]
Being that specific wasn't suitable for long: https://github.com/healthify/fake_idp/pull/49
